name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/inventory-dev:latest
          secrets: |
            "MONGOURI=${{ secrets.MONGOURI }}"
            "JWTSECRETADMIN=${{ secrets.JWTSECRETADMIN }}"
            "JWTSECRETSTAFF=${{ secrets.JWTSECRETSTAFF }}"
            "S3_BUCKETNAME=${{ secrets.S3_BUCKETNAME }}"
            "S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}"
            "S3_SIGNATUREVERSION=${{ secrets.S3_SIGNATUREVERSION }}"
            "S3_ACCESSKEYID=${{ secrets.S3_ACCESSKEYID }}"
            "S3_SECRETACCESSKEY=${{ secrets.S3_SECRETACCESSKEY }}"
            "PORT=${{ secrets.PORT }}"
